-- 029 — Le journal d'audit de la passerelle retrouve sa chaîne de hachage.
--
-- Les journaux Supabase montraient « column audit_events.seq_no does not exist » : la table de
-- base (007) n'avait que les colonnes de l'ancien journal WinnyWoo, alors que le lecteur et
-- l'écrivain (winny/common/audit_supabase.py) travaillent sur une chaîne : numéro d'ordre,
-- empreinte précédente, empreinte de la ligne. La page Audit échouait, et aucun événement
-- critique ne s'écrivait.

begin;

alter table public.audit_events add column if not exists seq_no bigint generated by default as identity;
alter table public.audit_events add column if not exists ts timestamptz not null default now();
alter table public.audit_events add column if not exists decision_id text;
alter table public.audit_events add column if not exists payload jsonb not null default '{}'::jsonb;
alter table public.audit_events add column if not exists prev_hash text;
alter table public.audit_events add column if not exists this_hash text;
alter table public.audit_events add column if not exists critical boolean not null default false;
alter table public.audit_events add column if not exists actor_email text;

-- L'écrivain chaîné ne remplit pas les colonnes de l'ancien journal.
alter table public.audit_events alter column action set default 'evenement';
alter table public.audit_events alter column component set default 'plateforme';
alter table public.audit_events alter column details set default '{}'::jsonb;

create unique index if not exists audit_events_seq_no_idx on public.audit_events (seq_no);
create unique index if not exists audit_events_this_hash_idx on public.audit_events (this_hash) where this_hash is not null;

commit;
